import { Knex } from 'knex';
import crypto from 'crypto';
import { v4 as uuidv4 } from 'uuid';

// Deterministic IDs so tests can reference them
const offerIds = Array.from({ length: 20 }, (_, i) =>
  uuidv4().replace(/^.{8}/, `offer${String(i + 1).padStart(3, '0')}`)
);

const segmentIds = {
  helloKitty: 'seg-hello-kitty-nights-001',
  nycEvents: 'seg-nyc-events-002',
  nbaTheme: 'seg-nba-theme-nights-003',
  mlbClassics: 'seg-mlb-classics-004',
  concertsLive: 'seg-concerts-live-005',
  familyFriendly: 'seg-family-friendly-006',
  premiumVip: 'seg-premium-vip-007',
  summerEvents: 'seg-summer-2026-008',
  msgVenue: 'seg-msg-venue-009',
  brooklynNights: 'seg-brooklyn-nights-010',
};

const API_KEY_RAW = 'efeed_test_key_abc123';

function hashKey(raw: string): string {
  return crypto.createHash('sha256').update(raw).digest('hex');
}

const now = new Date().toISOString();

const sampleOffers = [
  {
    id: offerIds[0],
    title: 'Hello Kitty Night at MSG',
    description: 'Special Hello Kitty themed night at Madison Square Garden',
    image_url: 'https://images.example.com/hello-kitty-msg.jpg',
    price_min: 45,
    price_max: 250,
    currency: 'USD',
    date: '2026-03-15T19:00:00Z',
    venue_name: 'Madison Square Garden',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-msg-001',
    organization_name: 'MSG Entertainment',
    checkout_url: 'https://checkout.example.com/hello-kitty-msg',
    tags: JSON.stringify(['hello-kitty', 'theme-night', 'nba']),
    status: 'active',
    distribution_enabled: true,
    distribution_enabled_at: now,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[1],
    title: 'Knicks vs Lakers - Hello Kitty Night',
    description: 'NBA game with Hello Kitty theme giveaways',
    image_url: 'https://images.example.com/knicks-hk.jpg',
    price_min: 60,
    price_max: 400,
    currency: 'USD',
    date: '2026-03-20T19:30:00Z',
    venue_name: 'Madison Square Garden',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-msg-001',
    organization_name: 'MSG Entertainment',
    checkout_url: 'https://checkout.example.com/knicks-lakers-hk',
    tags: JSON.stringify(['hello-kitty', 'nba', 'knicks']),
    status: 'active',
    distribution_enabled: true,
    distribution_enabled_at: now,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[2],
    title: 'Nets Fan Night at Barclays',
    description: 'Brooklyn Nets fan appreciation night',
    image_url: 'https://images.example.com/nets-fan-night.jpg',
    price_min: 35,
    price_max: 200,
    currency: 'USD',
    date: '2026-04-01T19:00:00Z',
    venue_name: 'Barclays Center',
    venue_city: 'Brooklyn',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-bsc-001',
    organization_name: 'BSE Global',
    checkout_url: 'https://checkout.example.com/nets-fan',
    tags: JSON.stringify(['nba', 'nets', 'fan-night']),
    status: 'active',
    distribution_enabled: true,
    distribution_enabled_at: now,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[3],
    title: 'Summer Jam Concert',
    description: 'Annual Summer Jam hip-hop concert',
    image_url: 'https://images.example.com/summer-jam.jpg',
    price_min: 75,
    price_max: 350,
    currency: 'USD',
    date: '2026-06-10T18:00:00Z',
    venue_name: 'MetLife Stadium',
    venue_city: 'East Rutherford',
    venue_state: 'NJ',
    availability: 'available',
    organization_id: 'org-hot97-001',
    organization_name: 'HOT 97',
    checkout_url: 'https://checkout.example.com/summer-jam',
    tags: JSON.stringify(['concert', 'hip-hop', 'summer']),
    status: 'active',
    distribution_enabled: true,
    distribution_enabled_at: now,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[4],
    title: 'Yankees vs Red Sox',
    description: 'Classic rivalry game at Yankee Stadium',
    image_url: 'https://images.example.com/yankees-redsox.jpg',
    price_min: 50,
    price_max: 500,
    currency: 'USD',
    date: '2026-05-20T19:05:00Z',
    venue_name: 'Yankee Stadium',
    venue_city: 'Bronx',
    venue_state: 'NY',
    availability: 'limited',
    organization_id: 'org-nyy-001',
    organization_name: 'New York Yankees',
    checkout_url: 'https://checkout.example.com/yankees-redsox',
    tags: JSON.stringify(['mlb', 'yankees', 'rivalry']),
    status: 'active',
    distribution_enabled: true,
    distribution_enabled_at: now,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[5],
    title: 'Mets Family Sunday',
    description: 'Family-friendly Sunday game at Citi Field',
    image_url: 'https://images.example.com/mets-family.jpg',
    price_min: 25,
    price_max: 150,
    currency: 'USD',
    date: '2026-05-25T13:00:00Z',
    venue_name: 'Citi Field',
    venue_city: 'Queens',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-mets-001',
    organization_name: 'New York Mets',
    checkout_url: 'https://checkout.example.com/mets-family',
    tags: JSON.stringify(['mlb', 'mets', 'family']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[6],
    title: 'Rangers Playoff Watch Party',
    description: 'Watch the Rangers playoff game on the big screen',
    image_url: 'https://images.example.com/rangers-watch.jpg',
    price_min: 15,
    price_max: 50,
    currency: 'USD',
    date: '2026-04-18T19:00:00Z',
    venue_name: 'Madison Square Garden',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-msg-001',
    organization_name: 'MSG Entertainment',
    checkout_url: 'https://checkout.example.com/rangers-watch',
    tags: JSON.stringify(['nhl', 'rangers', 'playoffs']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[7],
    title: 'Taylor Swift - Eras Tour NYC',
    description: 'Taylor Swift at MetLife Stadium',
    image_url: 'https://images.example.com/taylor-swift.jpg',
    price_min: 100,
    price_max: 1200,
    currency: 'USD',
    date: '2026-07-15T19:00:00Z',
    venue_name: 'MetLife Stadium',
    venue_city: 'East Rutherford',
    venue_state: 'NJ',
    availability: 'sold_out',
    organization_id: 'org-livenation-001',
    organization_name: 'Live Nation',
    checkout_url: 'https://checkout.example.com/taylor-swift',
    tags: JSON.stringify(['concert', 'pop', 'sold-out']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[8],
    title: 'NYCFC Match Day Experience',
    description: 'MLS game day with VIP experience',
    image_url: 'https://images.example.com/nycfc.jpg',
    price_min: 40,
    price_max: 180,
    currency: 'USD',
    date: '2026-04-10T16:00:00Z',
    venue_name: 'Yankee Stadium',
    venue_city: 'Bronx',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-nycfc-001',
    organization_name: 'NYCFC',
    checkout_url: 'https://checkout.example.com/nycfc-match',
    tags: JSON.stringify(['mls', 'soccer', 'vip']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[9],
    title: 'NBA All-Star Theme Night',
    description: 'All-Star themed event with celebrity appearances',
    image_url: 'https://images.example.com/nba-allstar.jpg',
    price_min: 80,
    price_max: 600,
    currency: 'USD',
    date: '2026-02-15T20:00:00Z',
    venue_name: 'Barclays Center',
    venue_city: 'Brooklyn',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-bsc-001',
    organization_name: 'BSE Global',
    checkout_url: 'https://checkout.example.com/nba-allstar',
    tags: JSON.stringify(['nba', 'all-star', 'theme-night']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[10],
    title: 'Comedy Night at The Garden',
    description: 'Stand-up comedy showcase at MSG Theater',
    image_url: 'https://images.example.com/comedy-msg.jpg',
    price_min: 55,
    price_max: 125,
    currency: 'USD',
    date: '2026-03-28T20:00:00Z',
    venue_name: 'Madison Square Garden',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-msg-001',
    organization_name: 'MSG Entertainment',
    checkout_url: 'https://checkout.example.com/comedy-msg',
    tags: JSON.stringify(['comedy', 'entertainment']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[11],
    title: 'Brooklyn Hip-Hop Festival',
    description: 'Annual hip-hop festival at Barclays Center',
    image_url: 'https://images.example.com/bk-hiphop.jpg',
    price_min: 65,
    price_max: 275,
    currency: 'USD',
    date: '2026-08-05T17:00:00Z',
    venue_name: 'Barclays Center',
    venue_city: 'Brooklyn',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-bsc-001',
    organization_name: 'BSE Global',
    checkout_url: 'https://checkout.example.com/bk-hiphop',
    tags: JSON.stringify(['concert', 'hip-hop', 'festival']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[12],
    title: 'LA Lakers Fan Experience',
    description: 'Exclusive Lakers fan event at Crypto.com Arena',
    image_url: 'https://images.example.com/lakers-fan.jpg',
    price_min: 50,
    price_max: 300,
    currency: 'USD',
    date: '2026-03-10T19:30:00Z',
    venue_name: 'Crypto.com Arena',
    venue_city: 'Los Angeles',
    venue_state: 'CA',
    availability: 'available',
    organization_id: 'org-lakers-001',
    organization_name: 'Los Angeles Lakers',
    checkout_url: 'https://checkout.example.com/lakers-fan',
    tags: JSON.stringify(['nba', 'lakers', 'fan-experience']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[13],
    title: 'Chicago Bulls Theme Night',
    description: '90s throwback theme night at United Center',
    image_url: 'https://images.example.com/bulls-theme.jpg',
    price_min: 40,
    price_max: 220,
    currency: 'USD',
    date: '2026-04-05T19:00:00Z',
    venue_name: 'United Center',
    venue_city: 'Chicago',
    venue_state: 'IL',
    availability: 'available',
    organization_id: 'org-bulls-001',
    organization_name: 'Chicago Bulls',
    checkout_url: 'https://checkout.example.com/bulls-theme',
    tags: JSON.stringify(['nba', 'bulls', 'theme-night', '90s']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[14],
    title: 'Warriors Tech Night',
    description: 'Silicon Valley tech-themed Warriors game',
    image_url: 'https://images.example.com/warriors-tech.jpg',
    price_min: 55,
    price_max: 350,
    currency: 'USD',
    date: '2026-04-12T19:30:00Z',
    venue_name: 'Chase Center',
    venue_city: 'San Francisco',
    venue_state: 'CA',
    availability: 'available',
    organization_id: 'org-warriors-001',
    organization_name: 'Golden State Warriors',
    checkout_url: 'https://checkout.example.com/warriors-tech',
    tags: JSON.stringify(['nba', 'warriors', 'tech', 'theme-night']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[15],
    title: 'Sold Out Concert (Inactive)',
    description: 'This event was canceled',
    image_url: 'https://images.example.com/canceled.jpg',
    price_min: 30,
    price_max: 100,
    currency: 'USD',
    date: '2026-02-01T20:00:00Z',
    venue_name: 'Radio City Music Hall',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'sold_out',
    organization_id: 'org-msg-001',
    organization_name: 'MSG Entertainment',
    checkout_url: 'https://checkout.example.com/canceled',
    tags: JSON.stringify(['concert', 'canceled']),
    status: 'inactive',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[16],
    title: 'Deleted Test Offer',
    description: 'This offer was deleted',
    image_url: null,
    price_min: null,
    price_max: null,
    currency: 'USD',
    date: null,
    venue_name: null,
    venue_city: null,
    venue_state: null,
    availability: 'available',
    organization_id: 'org-test-001',
    organization_name: 'Test Org',
    checkout_url: null,
    tags: null,
    status: 'deleted',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[17],
    title: 'Miami Heat Beach Night',
    description: 'Beach-themed NBA night at FTX Arena',
    image_url: 'https://images.example.com/heat-beach.jpg',
    price_min: 45,
    price_max: 280,
    currency: 'USD',
    date: '2026-04-20T19:30:00Z',
    venue_name: 'Kaseya Center',
    venue_city: 'Miami',
    venue_state: 'FL',
    availability: 'available',
    organization_id: 'org-heat-001',
    organization_name: 'Miami Heat',
    checkout_url: 'https://checkout.example.com/heat-beach',
    tags: JSON.stringify(['nba', 'heat', 'beach', 'theme-night']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[18],
    title: 'Hello Kitty Cafe Pop-Up',
    description: 'Hello Kitty themed pop-up cafe event',
    image_url: 'https://images.example.com/hk-cafe.jpg',
    price_min: 20,
    price_max: 60,
    currency: 'USD',
    date: '2026-05-01T11:00:00Z',
    venue_name: 'Hudson Yards',
    venue_city: 'New York',
    venue_state: 'NY',
    availability: 'available',
    organization_id: 'org-sanrio-001',
    organization_name: 'Sanrio Events',
    checkout_url: 'https://checkout.example.com/hk-cafe',
    tags: JSON.stringify(['hello-kitty', 'pop-up', 'cafe']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: offerIds[19],
    title: 'Celtics vs Knicks Rivalry Night',
    description: 'Historic rivalry game at TD Garden',
    image_url: 'https://images.example.com/celtics-knicks.jpg',
    price_min: 70,
    price_max: 450,
    currency: 'USD',
    date: '2026-04-25T19:00:00Z',
    venue_name: 'TD Garden',
    venue_city: 'Boston',
    venue_state: 'MA',
    availability: 'available',
    organization_id: 'org-celtics-001',
    organization_name: 'Boston Celtics',
    checkout_url: 'https://checkout.example.com/celtics-knicks',
    tags: JSON.stringify(['nba', 'celtics', 'rivalry']),
    status: 'active',
    distribution_enabled: false,
    distribution_enabled_at: null,
    distribution_disabled_at: null,
    created_at: now,
    updated_at: now,
  },
];

// ── Organizations ──────────────────────────────────────────────────────────

const sampleOrganizations = [
  { id: 'org-msg-001', name: 'MSG Entertainment', logo_url: 'https://logo.clearbit.com/msg.com', fevo_org_id: 'fevo-org-1001', created_at: now, updated_at: now },
  { id: 'org-bsc-001', name: 'BSE Global', logo_url: 'https://logo.clearbit.com/bfriesents.com', fevo_org_id: 'fevo-org-1002', created_at: now, updated_at: now },
  { id: 'org-hot97-001', name: 'HOT 97', logo_url: 'https://logo.clearbit.com/hot97.com', fevo_org_id: 'fevo-org-1003', created_at: now, updated_at: now },
  { id: 'org-nyy-001', name: 'New York Yankees', logo_url: 'https://logo.clearbit.com/yankees.com', fevo_org_id: 'fevo-org-1004', created_at: now, updated_at: now },
  { id: 'org-mets-001', name: 'New York Mets', logo_url: 'https://logo.clearbit.com/mets.com', fevo_org_id: 'fevo-org-1005', created_at: now, updated_at: now },
  { id: 'org-nycfc-001', name: 'NYCFC', logo_url: 'https://logo.clearbit.com/newyorkcityfc.com', fevo_org_id: 'fevo-org-1006', created_at: now, updated_at: now },
  { id: 'org-livenation-001', name: 'Live Nation', logo_url: 'https://logo.clearbit.com/livenation.com', fevo_org_id: 'fevo-org-1007', created_at: now, updated_at: now },
  { id: 'org-lakers-001', name: 'Los Angeles Lakers', logo_url: 'https://logo.clearbit.com/lakers.com', fevo_org_id: 'fevo-org-1008', created_at: now, updated_at: now },
  { id: 'org-bulls-001', name: 'Chicago Bulls', logo_url: 'https://logo.clearbit.com/bulls.com', fevo_org_id: 'fevo-org-1009', created_at: now, updated_at: now },
  { id: 'org-warriors-001', name: 'Golden State Warriors', logo_url: 'https://logo.clearbit.com/warriors.com', fevo_org_id: 'fevo-org-1010', created_at: now, updated_at: now },
  { id: 'org-heat-001', name: 'Miami Heat', logo_url: 'https://logo.clearbit.com/heat.com', fevo_org_id: 'fevo-org-1011', created_at: now, updated_at: now },
  { id: 'org-sanrio-001', name: 'Sanrio Events', logo_url: 'https://logo.clearbit.com/sanrio.com', fevo_org_id: 'fevo-org-1012', created_at: now, updated_at: now },
  { id: 'org-celtics-001', name: 'Boston Celtics', logo_url: 'https://logo.clearbit.com/celtics.com', fevo_org_id: 'fevo-org-1013', created_at: now, updated_at: now },
  { id: 'org-test-001', name: 'Test Org', logo_url: null, fevo_org_id: null, created_at: now, updated_at: now },
  // Additional organizations
  { id: 'org-76ers-001', name: 'Philadelphia 76ers', logo_url: 'https://logo.clearbit.com/sixers.com', fevo_org_id: 'fevo-org-1014', created_at: now, updated_at: now },
  { id: 'org-raptors-001', name: 'Toronto Raptors', logo_url: 'https://logo.clearbit.com/raptors.com', fevo_org_id: 'fevo-org-1015', created_at: now, updated_at: now },
  { id: 'org-redsox-001', name: 'Boston Red Sox', logo_url: 'https://logo.clearbit.com/redsox.com', fevo_org_id: 'fevo-org-1016', created_at: now, updated_at: now },
  { id: 'org-dodgers-001', name: 'Los Angeles Dodgers', logo_url: 'https://logo.clearbit.com/dodgers.com', fevo_org_id: 'fevo-org-1017', created_at: now, updated_at: now },
  { id: 'org-chiefs-001', name: 'Kansas City Chiefs', logo_url: 'https://logo.clearbit.com/chiefs.com', fevo_org_id: 'fevo-org-1018', created_at: now, updated_at: now },
  { id: 'org-cowboys-001', name: 'Dallas Cowboys', logo_url: 'https://logo.clearbit.com/dallascowboys.com', fevo_org_id: 'fevo-org-1019', created_at: now, updated_at: now },
  { id: 'org-aeg-001', name: 'AEG Presents', logo_url: 'https://logo.clearbit.com/aegpresents.com', fevo_org_id: 'fevo-org-1020', created_at: now, updated_at: now },
  { id: 'org-bowery-001', name: 'Bowery Presents', logo_url: 'https://logo.clearbit.com/bowerypresents.com', fevo_org_id: 'fevo-org-1021', created_at: now, updated_at: now },
  { id: 'org-bklyn-001', name: 'Brooklyn Sports & Entertainment', logo_url: 'https://logo.clearbit.com/brooklynse.com', fevo_org_id: 'fevo-org-1022', created_at: now, updated_at: now },
  { id: 'org-islanders-001', name: 'New York Islanders', logo_url: 'https://logo.clearbit.com/newyorkislanders.com', fevo_org_id: 'fevo-org-1023', created_at: now, updated_at: now },
];

// ── Venues ──────────────────────────────────────────────────────────────────

const sampleVenues = [
  { id: 'venue-msg-001', name: 'Madison Square Garden', city: 'New York', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-barclays-001', name: 'Barclays Center', city: 'Brooklyn', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-metlife-001', name: 'MetLife Stadium', city: 'East Rutherford', state: 'NJ', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-yankee-001', name: 'Yankee Stadium', city: 'Bronx', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-citi-001', name: 'Citi Field', city: 'Queens', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-crypto-001', name: 'Crypto.com Arena', city: 'Los Angeles', state: 'CA', country: 'US', timezone: 'America/Los_Angeles', created_at: now, updated_at: now },
  { id: 'venue-united-001', name: 'United Center', city: 'Chicago', state: 'IL', country: 'US', timezone: 'America/Chicago', created_at: now, updated_at: now },
  { id: 'venue-chase-001', name: 'Chase Center', city: 'San Francisco', state: 'CA', country: 'US', timezone: 'America/Los_Angeles', created_at: now, updated_at: now },
  { id: 'venue-rcmh-001', name: 'Radio City Music Hall', city: 'New York', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-kaseya-001', name: 'Kaseya Center', city: 'Miami', state: 'FL', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-hudson-001', name: 'Hudson Yards', city: 'New York', state: 'NY', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
  { id: 'venue-td-001', name: 'TD Garden', city: 'Boston', state: 'MA', country: 'US', timezone: 'America/New_York', created_at: now, updated_at: now },
];

export async function seed(knex: Knex): Promise<void> {
  // Clean tables in dependency order
  await knex('event_feed_segment_offers').del();
  await knex('event_feed_segments').del();
  await knex('feed_exclusions').del();
  await knex('event_feed_kills').del();
  await knex('feed_cache').del();
  await knex('api_keys').del();
  await knex('sync_log').del();
  await knex('offers').del();
  await knex('events').del();
  await knex('venues').del();
  await knex('organizations').del();

  // Insert organizations
  await knex('organizations').insert(sampleOrganizations);

  // Insert venues
  await knex('venues').insert(sampleVenues);

  // Insert offers
  await knex('offers').insert(sampleOffers);

  // Insert segments (annotated as [Test] stub data)
  await knex('event_feed_segments').insert([
    {
      id: segmentIds.helloKitty,
      name: '[Test] Hello Kitty Nights',
      slug: 'hello-kitty-nights',
      type: 'theme',
      rules: JSON.stringify({ tags_include: ['hello-kitty'] }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.nycEvents,
      name: '[Test] NYC Events',
      slug: 'nyc-events',
      type: 'geography',
      rules: JSON.stringify({ venue_state: 'NY' }),
      is_curated: false,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.nbaTheme,
      name: '[Test] NBA Theme Nights',
      slug: 'nba-theme-nights',
      type: 'theme',
      rules: JSON.stringify({ tags_include: ['nba', 'theme-night'] }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.mlbClassics,
      name: '[Test] MLB Classics',
      slug: 'mlb-classics',
      type: 'theme',
      rules: JSON.stringify({ tags_include: ['mlb'] }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.concertsLive,
      name: '[Test] Concerts & Live Music',
      slug: 'concerts-live',
      type: 'theme',
      rules: JSON.stringify({ tags_include: ['concert'] }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.familyFriendly,
      name: '[Test] Family Friendly',
      slug: 'family-friendly',
      type: 'custom',
      rules: JSON.stringify({ tags_include: ['family'] }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.premiumVip,
      name: '[Test] Premium & VIP',
      slug: 'premium-vip',
      type: 'custom',
      rules: JSON.stringify({ price_min_gte: 100 }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.summerEvents,
      name: '[Test] Summer 2026',
      slug: 'summer-2026',
      type: 'theme',
      rules: JSON.stringify({ tags_include: ['summer'] }),
      is_curated: false,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.msgVenue,
      name: '[Test] MSG Entertainment',
      slug: 'msg-entertainment',
      type: 'partner',
      rules: JSON.stringify({ organization_id: 'org-msg-001' }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
    {
      id: segmentIds.brooklynNights,
      name: '[Test] Brooklyn Nights',
      slug: 'brooklyn-nights',
      type: 'geography',
      rules: JSON.stringify({ venue_city: 'Brooklyn' }),
      is_curated: true,
      created_by: 'admin (stub)',
      created_at: now,
      updated_at: now,
    },
  ]);

  // Link offers to segments
  await knex('event_feed_segment_offers').insert([
    // Hello Kitty Nights — 2 offers
    { segment_id: segmentIds.helloKitty, offer_id: offerIds[0], added_at: now },
    { segment_id: segmentIds.helloKitty, offer_id: offerIds[1], added_at: now },
    // NBA Theme Nights — 4 offers (all NBA-tagged)
    { segment_id: segmentIds.nbaTheme, offer_id: offerIds[0], added_at: now },
    { segment_id: segmentIds.nbaTheme, offer_id: offerIds[1], added_at: now },
    { segment_id: segmentIds.nbaTheme, offer_id: offerIds[2], added_at: now },
    { segment_id: segmentIds.nbaTheme, offer_id: offerIds[9], added_at: now },
    // MLB Classics — 2 offers (Yankees, Mets)
    { segment_id: segmentIds.mlbClassics, offer_id: offerIds[4], added_at: now },
    { segment_id: segmentIds.mlbClassics, offer_id: offerIds[5], added_at: now },
    // Concerts & Live Music — 3 offers
    { segment_id: segmentIds.concertsLive, offer_id: offerIds[3], added_at: now },
    { segment_id: segmentIds.concertsLive, offer_id: offerIds[7], added_at: now },
    { segment_id: segmentIds.concertsLive, offer_id: offerIds[11], added_at: now },
    // Family Friendly — 2 offers
    { segment_id: segmentIds.familyFriendly, offer_id: offerIds[5], added_at: now },
    { segment_id: segmentIds.familyFriendly, offer_id: offerIds[8], added_at: now },
    // Premium & VIP — 3 offers (high-price events)
    { segment_id: segmentIds.premiumVip, offer_id: offerIds[7], added_at: now },
    { segment_id: segmentIds.premiumVip, offer_id: offerIds[4], added_at: now },
    { segment_id: segmentIds.premiumVip, offer_id: offerIds[9], added_at: now },
    // MSG Entertainment — 5 offers (all MSG)
    { segment_id: segmentIds.msgVenue, offer_id: offerIds[0], added_at: now },
    { segment_id: segmentIds.msgVenue, offer_id: offerIds[1], added_at: now },
    { segment_id: segmentIds.msgVenue, offer_id: offerIds[6], added_at: now },
    { segment_id: segmentIds.msgVenue, offer_id: offerIds[10], added_at: now },
    { segment_id: segmentIds.msgVenue, offer_id: offerIds[14], added_at: now },
    // Brooklyn Nights — 3 offers (Brooklyn venue)
    { segment_id: segmentIds.brooklynNights, offer_id: offerIds[2], added_at: now },
    { segment_id: segmentIds.brooklynNights, offer_id: offerIds[11], added_at: now },
    { segment_id: segmentIds.brooklynNights, offer_id: offerIds[16], added_at: now },
  ]);

  // Insert sample API key
  await knex('api_keys').insert({
    id: uuidv4(),
    key_hash: hashKey(API_KEY_RAW),
    partner_name: 'Test Partner',
    created_at: now,
    revoked_at: null,
    rate_limit: 100,
  });
}
